### ISSUE TITLE
New key in requested login data

### ISSUE THREAD

**Issue by SchnappiWappi** [blue1stone/python-bring-api#5]
Hey there!
I love this api and it's a great modul to start programming for beginner projects. Thank you for posting!

Sadly I cannot login with my registration data.
line 60 in the Bring class has a key Error for 'name'

I think that I already found the solution.
the keys in the requested data-dictionary has been changed. If you print the r.json(), you will see that instead of 'name' there will be an 'email' key. 
By changing line 60 to:

self.name = data['email']

it works like a champ again.

Since I am a beginner and admit that this is still a very complex modul for my experience, I would ask for your input. Maybe I got something wrong in the first place? Anyway, thank you so much for creating this modul!

**Comment by eliasball** [comment]
Hey there!
Thanks a lot for your issue, I am really glad you like the module! :)
When I tested everything locally, it worked for me. I sadly couldn't replicate the issue.
Nonetheless, I found out that getting the `name` or `email` field seems to not be necessary for the API to work anyway. So I removed them. You hopefully shouldn't have any problems anymore! If you do, feel free to write again :)
